# Generated by Django 2.0.7 on 2019-03-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0002_auto_20190312_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfastho',
            name='Picture',
        ),
    ]
