# Generated by Django 2.0.7 on 2019-03-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0003_remove_breakfastho_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastho',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
