# Generated by Django 2.0.7 on 2019-03-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
