# Generated by Django 2.0.7 on 2019-03-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Picture',
            new_name='image',
        ),
    ]
