# Generated by Django 2.0.7 on 2019-03-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='payment',
            field=models.ImageField(default='', upload_to='static/'),
            preserve_default=False,
        ),
    ]
