# Generated by Django 2.0.7 on 2019-03-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
