# Generated by Django 2.0.7 on 2019-03-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=5),
            preserve_default=False,
        ),
    ]
