# Generated by Django 2.0.7 on 2019-03-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosomething',
            name='bigshit',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
