# Generated by Django 2.0.7 on 2019-03-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_dosomething_bigshit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosomething',
            name='time',
            field=models.DateTimeField(default='2006-10-25'),
            preserve_default=False,
        ),
    ]
