# Generated by Django 2.0.7 on 2019-03-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0003_dosomething_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosomething',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
