# Generated by Django 2.0.7 on 2019-03-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_auto_20190312_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosomething',
            name='ass',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dosomething',
            name='bigshit',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dosomething',
            name='shit',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dosomething',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dosomething',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
